<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<title>Entries</title>
	</head>
	<body>
		<section id="content">
			<h1>Entries</h1>
			
			<table>
				<thead>
					<tr>
						<th scope="col">Id</th>
						<th scope="col">Description</th>
					</tr>
				</thead>
				<tfoot>
					<tr>
						<td colspan="2"><?php echo $this->paginationControl($this->entries, 'sliding', 'pagination.phtml'); ?></td>
					</tr>
				</tfoot>
				<tbody>
					<?php if (sizeof($this->entries) == 0): ?>
					<tr>
						<td colspan="2">No entries found</td>
					</tr>
					<?php else: ?>
					<?php foreach ($this->entries as $entry): ?>
					<tr>
						<td><?php echo $entry->getId(); ?></td>
						<td><?php echo $entry->getDescription(); ?></td>
					</tr>
					<?php endforeach; ?>
					<?php endif; ?>
				</tbody>
			</table>
		</section>
	</body>
</html>